### ISSUE TITLE
"uv_polygen_calc.rb" single numeric inputs cannot begin with a decimal separator

### ISSUE THREAD

**Issue by DanRathbun** [jimhami42/UV_PolyGen#13]
"uv_polygen_calc.rb" 

Single numeric inputs cannot begin with a decimal separator. Currently the regular expression that checks for fields beginning with non-numeric characters, see them as no-numeric, and so they get passed to evaluation.

Sometime prior to Ruby 1.8.6-p287, the Ruby interpreter was changed and literal numerics cannot begin with a decimal point (regardless of a sign character.)

Change the "Non-digit beginning" regular expression in the **if** expression of **float()**, to recognize beginning decimal point or comma as numeric characters. This will cause the inputs to be passed to the **else** clause, where the comma will be replaced with a decimal point, and the input is passed to **String#to_f**, which does not mind no zero before decimal point. 

This is labeled an enhancement, because it is unlikely that we can correct poorly written complex expressions, in all cases.

So the "rule of thumb" will be make it easier on Ruby, "Start a decimal fraction with a zero, please."

**Comment by jimhami42** [comment]
Hi Dan -

I had a chance to finally look through your code in detail yesterday and I
am still marveling at the amount of code you've wrapped around everything.
I was wondering about the leading decimal issue (i.e., "-.5", ".5", etc.).
Could a simple substitution like:

  t.gsub!(/([^0-9]_).([0-9]_)/,'\10.\2')

be applied before anything else? However, this would cause a problem with
something like Abcdef.3Dghijk function calls (or other somesuch).

Just a thought ...

Jim

**Comment by DanRathbun** [comment]
Yes I was trying similar arguments last night, like:
**`str.gsub!(/\.(?=re)[0-9]/,'0\1')`**, which didn't quite work. It was midnight so I gave up, ...

Yours was _almost_ correct, but better than mine. This works:

``` ruby
t = "(+.3 / +2.6 * (-.5 + .7))"
re = /([^0-9]+)\.([0-9]*)/i
t.gsub(re,'\10.\2')
>> "(+0.3 / +2.6 * (-0.5 + 0.7))"
```

The first match needs to be on **`[^0-9]+`** (1 or more non-numerics,) otherwise a zero gets inserted into **`+2.6`**, making it **`+20.6`**.

**Comment by jimhami42** [comment]
> The first match needs to be on _[^0-9]+_ (1 or more non-numerics,)
> otherwise a zero gets inserted into _+2.6_, making it _+20.6_.

I was trying to match "none" for a simple case like ".5" by itself ... I
think maybe this is closer to what we want (also works with commas):

t1.gsub!(/(\A|[^0-9])([.,])([0-9])/,'\10\2\3')

2.5 + .2_cos(.14) / .15_cos(.2) ------> 2.5 + 0.2_cos(0.14) / 0.15_cos(0.2)

,5 + 1,2_cos(,14) / ,15_cos(2.2) ----> 0,5 + 1,2_cos(0,14) / 0,15_cos(2.2)

**Comment by DanRathbun** [comment]
Well, you used a ***** modifier, which means "0 or more". I added a **+** which forces a match on **at least 1**.

But a character class like `[^0-9]` implies **1 and only 1**, which is all we really need.

**Comment by DanRathbun** [comment]
> maybe this is closer to what we want (also works with commas):
> 
> `t1.gsub!(/(\A|[^0-9])([.,])([0-9])/,'\10\2\3')`

This is in the **if** clause which handles evaluation rather than conversion, (done in the **else** clause. The starting numeric handler in the **else** clause uses **String#to_f** which has no problem converting strings that have no zero in front of the decimal point.)

At this point in the **if** clause I have already replaced all commas with decimal points, and all semi-colons with commas, but only within a conditional **`if  !DECPT`** block, (meaning the user likely uses comma as a decimal separator.)
