### ISSUE TITLE
Is offset input field unitless or entered in model units ?

### ISSUE THREAD

**Issue by DanRathbun** [jimhami42/UV_PolyGen#18]
**Is offset input field unitless or entered in model units ?**

There seems to be an error in the display of the offset value when a below tolerance value is entered.

Change model units to decimal **mm**. And enter 0.001 as the offset.

**offset** should be `0.001 * (1.0/25.4) = 3.937e-05`
but

``` ruby
Sketchup.format_length(3.937e-05)
>> 0.001mm
```

And that is what is displayed in the caption of the inputbox.

[ref "uv_polygen_core.rb" : line 820]

**Comment by jimhami42** [comment]
The offset should be in model units ... if it's 0.001 mm, then that works out to about 0.00003937" which is obviously less than the 0.001" limit. If they're working in mm, then the offset should be greater than or equal to 0.0254 mm (if not == 0.0). Entering 0.001 mm would be too small of a number to be acceptable. Whichever the units, the minimum distance should be the equivalent of 0.001" ... in meters, this would be 0.0000254 m.

**Comment by DanRathbun** [comment]
OK, so now I am confused. Last cycle I asked if it needed to be scaled to the model unit and you told me yes, so I did that, but this seems not to be correct.

Do I really need to be assuming offset is in model units (no scaling needed,) converting to inches internally, and using **Sketchup.format_length()** to display the error message ?
